/**
 * The systems catalog's icons, rendered as React elements.
 *
 * ## Why not `dangerouslySetInnerHTML`
 *
 * The catalog carries each system's glyph as it appears on the portal, and the
 * tempting shortcut is to paste that markup into the DOM. That would make
 * `systems.json` — a file regenerated by a script from a remote page — a
 * script-injection surface, and would put the safety of the drawer at the mercy
 * of whatever the portal serves next. The sync script therefore decomposes each
 * `<svg>` into a closed vocabulary (`path` / `circle` / `rect` / `line` with a
 * whitelisted attribute set), and this module renders that vocabulary as real
 * elements. Anything outside it was dropped at sync time, and
 * `tests/catalog.spec.ts` asserts the vocabulary from both ends.
 *
 * ## Why the attributes are translated instead of spread
 *
 * The catalog stores SVG attributes in their markup spelling (`stroke-width`),
 * because that is what the page said and re-spelling it in the data would be a
 * transformation nobody could re-derive. React wants the DOM property spelling
 * (`strokeWidth`), so the translation happens here, where it is one table and
 * one place to be wrong. `fill` and `stroke` are left as they come: the portal
 * draws with `currentColor`, which is what lets the same glyph follow the theme
 * and turn brand-deep on hover without a second copy of the file.
 *
 * @module dsh-newapp-local/client/SystemIcon
 */
import type { JSX } from 'react'
import type { IconShape } from './systems.ts'

/**
 * Markup-spelled SVG attributes → their React DOM property names.
 *
 * Only the four the portal actually uses. An attribute that is not here and not
 * already a valid React name is dropped rather than spread, so a future portal
 * attribute cannot reach the DOM unfiltered.
 */
const REACT_ATTR: Record<string, string> = {
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
}

/** Attributes passed through unchanged — already spelled the way React wants. */
const PASSTHROUGH = new Set(['d', 'cx', 'cy', 'r', 'x', 'y', 'width', 'height', 'rx', 'fill', 'stroke'])

/**
 * One system's glyph.
 * @param props - the shape list from the catalog, and the rendered size.
 * @returns an `<svg>` at the shell's icon scale.
 */
export function SystemIcon({
  shapes,
  size = 20,
}: {
  shapes: readonly IconShape[]
  size?: number
}): JSX.Element {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      {shapes.map((shape, index) => {
        const props: Record<string, string> = {}
        for (const [key, value] of Object.entries(shape.attrs)) {
          const name = REACT_ATTR[key] ?? (PASSTHROUGH.has(key) ? key : undefined)
          if (name !== undefined) props[name] = value
        }
        // Shape order is the drawing order — the portal stacks strokes to build
        // the glyph, so the index is the React key and the render order both.
        const key = `${shape.tag}-${String(index)}`
        if (shape.tag === 'path') return <path key={key} {...props} />
        if (shape.tag === 'circle') return <circle key={key} {...props} />
        if (shape.tag === 'rect') return <rect key={key} {...props} />
        if (shape.tag === 'line') return <line key={key} {...props} />
        // Unreachable through the catalog's asserted vocabulary. Rendering
        // nothing is the right failure: a shape the renderer does not know is
        // not something to guess at.
        return null
      })}
    </svg>
  )
}
