/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'source': z.string().readonly(),
  'url': z.union([z.undefined(), z.string()]).readonly().optional(),
  'snippet': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sources': z.union([z.undefined(), z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
}))]).readonly().optional(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_complete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'report': z.string().readonly(),
  'conclusions': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'limitations': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'partial': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_complete_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_delete_result$schema = z.object({
  'deleted': z.boolean().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_fail_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'reason': z.string().readonly(),
  'aborted': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_fail_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_get_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_get_result$schema = z.union([z.literal(null), z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})])
const _deepseek_ai_dsh_deepresearch_deepResearch_list_parameter_0$schema = z.object({
  'query': z.string().readonly().optional(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_list_result$schema = z.object({
  'projects': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_resume_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_resume_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_start_parameter_0$schema = z.object({
  'title': z.string().readonly().optional(),
  'question': z.string().readonly(),
  'goal': z.string().readonly().optional(),
  'constraints': z.string().readonly().optional(),
  'seedText': z.string().readonly().optional(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'questions': z.array(z.object({
  'text': z.string().readonly(),
  'criteria': z.array(z.string()).readonly(),
  'dependsOn': z.array(z.number()).readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_start_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'questions': z.array(z.object({
  'text': z.string().readonly(),
  'criteria': z.array(z.string()).readonly(),
  'dependsOn': z.array(z.number()).readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly().optional(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_writeReport_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_deepresearch_deepResearch_writeReport_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'question': z.string().readonly(),
  'goal': z.string().readonly(),
  'constraints': z.string().readonly(),
  'seedText': z.string().readonly(),
  'depth': z.union([z.literal("quick"), z.literal("standard"), z.literal("deep")]).readonly(),
  'phase': z.union([z.literal("failed"), z.literal("planning"), z.literal("awaiting_plan_confirm"), z.literal("investigating"), z.literal("ready_for_report"), z.literal("incomplete"), z.literal("writing"), z.literal("done"), z.literal("aborted")]).readonly(),
  'runState': z.union([z.literal("running"), z.literal("idle"), z.literal("paused")]).readonly(),
  'planConfirmed': z.boolean().readonly(),
  'questions': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'text': z.string().readonly(),
  'dependsOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'status': z.union([z.literal("running"), z.literal("failed"), z.literal("pending"), z.literal("covered"), z.literal("partial"), z.literal("blocked")]).readonly(),
  'criteria': z.array(z.object({
  'id': z.string().readonly(),
  'text': z.string().readonly(),
  'status': z.union([z.literal("covered"), z.literal("partial"), z.literal("blocked"), z.literal("missing"), z.literal("conflicted")]).readonly(),
  'summary': z.string().readonly(),
  'gap': z.string().readonly(),
  'warning': z.string().readonly(),
  'verification': z.union([z.literal(""), z.literal("PASS"), z.literal("WARNING"), z.literal("FAIL")]).readonly(),
  'toolCount': z.number().readonly(),
})).readonly(),
  'gaps': z.array(z.string()).readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
  'evidence': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'criterionIds': z.array(z.string()).readonly(),
  'source': z.string().readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snippet': z.string().readonly(),
  'sources': z.array(z.object({
  'url': z.string().readonly(),
  'snippet': z.string().readonly(),
  'artifactId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'claim': z.string().readonly(),
  'confidence': z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'status': z.union([z.literal("rejected"), z.literal("candidate"), z.literal("accepted")]).readonly(),
  'createdAt': z.number().readonly(),
})).readonly(),
  'conclusions': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'report': z.union([z.literal(null), z.string()]).readonly(),
  'budget': z.object({
  'maxSearches': z.number().readonly(),
  'maxFetches': z.number().readonly(),
  'searchesUsed': z.number().readonly(),
  'fetchesUsed': z.number().readonly(),
}).readonly(),
  'progress': z.object({
  'running': z.number().readonly(),
  'waiting': z.number().readonly(),
  'scouts': z.array(z.object({
  'questionId': z.intersection(z.string(), z.unknown()).readonly(),
  'role': z.union([z.literal("waiting"), z.literal("writing"), z.literal("scout"), z.literal("evaluator")]).readonly(),
  'status': z.union([z.literal("running"), z.literal("waiting"), z.literal("done"), z.literal("partial"), z.literal("blocked"), z.literal("verifying")]).readonly(),
  'waitingOn': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'toolsUsed': z.number().readonly(),
  'toolsCap': z.number().readonly(),
  'activity': z.string().readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'detail': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("done")]).readonly(),
})).readonly(),
  'scoutDraft': z.string().readonly(),
  'evaluatorDraft': z.string().readonly(),
  'activeCriterionId': z.string().readonly(),
  'activeCriterionText': z.string().readonly(),
  'dependencySummary': z.string().readonly(),
  'handoff': z.string().readonly(),
})).readonly(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-deepresearch',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/addEvidence',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'addEvidence',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchEvidenceRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_addEvidence_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":174,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/complete',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'complete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchCompleteRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_complete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_complete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":208,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/confirmPlan',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'confirmPlan',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchConfirmRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_confirmPlan_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":164,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/delete',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchDeleteRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchDeleteResult',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_delete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":254,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/fail',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'fail',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchFailRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_fail_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_fail_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":220,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/get',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchGetRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch#deepResearch/get:result',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_get_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":127,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/list',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchListRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchListResult',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":121,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/resume',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchResumeRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_resume_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_resume_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":228,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/start',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'start',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchStartRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_start_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_start_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":130,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/updatePlan',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'updatePlan',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchPlanUpdateRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_updatePlan_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":154,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/updateQuestion',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'updateQuestion',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchQuestionUpdateRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_updateQuestion_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":195,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-deepresearch#deepResearch/writeReport',
      service: 'deepResearch',
      namespace: 'deepResearch',
      method: 'writeReport',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchWriteReportRequest',
            schema: _deepseek_ai_dsh_deepresearch_deepResearch_writeReport_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-deepresearch/types#ResearchProject',
        schema: _deepseek_ai_dsh_deepresearch_deepResearch_writeReport_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/deepresearch/src/index.ts","line":240,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable Codemini-style Deep Research project service.",
        "summary": "Durable Codemini-style Deep Research project service.",
        "tags": [],
        "jsDoc": "/** Durable Codemini-style Deep Research project service. */",
        "key": "deepResearch",
        "exportName": "DeepResearchService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: ResearchListRequest): ResearchListResult"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(request: ResearchGetRequest): ResearchProject | null"
          },
          {
            "kind": "method",
            "name": "start",
            "signature": "@Remote('start') start(request: ResearchStartRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "updatePlan",
            "signature": "@Remote('updatePlan') updatePlan(request: ResearchPlanUpdateRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "confirmPlan",
            "signature": "@Remote('confirmPlan') async confirmPlan(request: ResearchConfirmRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "addEvidence",
            "signature": "@Remote('addEvidence') addEvidence(request: ResearchEvidenceRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "updateQuestion",
            "signature": "@Remote('updateQuestion') updateQuestion(request: ResearchQuestionUpdateRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "complete",
            "signature": "@Remote('complete') complete(request: ResearchCompleteRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "fail",
            "signature": "@Remote('fail') fail(request: ResearchFailRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "resume",
            "signature": "@Remote('resume') async resume(request: ResearchResumeRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "writeReport",
            "signature": "@Remote('writeReport') async writeReport(request: ResearchWriteReportRequest): Promise<ResearchProject>"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: ResearchDeleteRequest): Promise<ResearchDeleteResult>"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ResearchBudget",
            "declaration": "export interface ResearchBudget {\n    readonly maxSearches: number;\n    readonly maxFetches: number;\n    readonly searchesUsed: number;\n    readonly fetchesUsed: number;\n}"
          },
          {
            "name": "ResearchCompleteRequest",
            "declaration": "export interface ResearchCompleteRequest {\n    readonly id: ResearchId;\n    readonly report: string;\n    readonly conclusions?: string[] | undefined;\n    readonly limitations?: string[] | undefined;\n    readonly partial?: boolean | undefined;\n}"
          },
          {
            "name": "ResearchConfidence",
            "declaration": "export type ResearchConfidence = 'low' | 'medium' | 'high';"
          },
          {
            "name": "ResearchConfirmRequest",
            "declaration": "export interface ResearchConfirmRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchCoverageStatus",
            "declaration": "export type ResearchCoverageStatus = 'missing' | 'partial' | 'covered' | 'conflicted' | 'blocked';"
          },
          {
            "name": "ResearchCriterion",
            "declaration": "export interface ResearchCriterion {\n    readonly id: string;\n    readonly text: string;\n    readonly status: ResearchCoverageStatus;\n    readonly summary: string;\n    readonly gap: string;\n    readonly warning: string;\n    readonly verification: ResearchVerification;\n    readonly toolCount: number;\n}"
          },
          {
            "name": "ResearchDeleteRequest",
            "declaration": "export interface ResearchDeleteRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchDeleteResult",
            "declaration": "export interface ResearchDeleteResult {\n    readonly deleted: boolean;\n}"
          },
          {
            "name": "ResearchDepth",
            "declaration": "export type ResearchDepth = 'quick' | 'standard' | 'deep';"
          },
          {
            "name": "ResearchEvidence",
            "declaration": "export interface ResearchEvidence {\n    readonly id: ResearchEvidenceId;\n    readonly questionId: ResearchQuestionId;\n    readonly criterionIds: string[];\n    readonly source: string;\n    readonly url: string | null;\n    readonly snippet: string;\n    readonly sources: ResearchEvidenceSource[];\n    readonly claim: string;\n    readonly confidence: ResearchConfidence;\n    readonly status: ResearchEvidenceStatus;\n    readonly createdAt: number;\n}"
          },
          {
            "name": "ResearchEvidenceId",
            "declaration": "export type ResearchEvidenceId = Branded<'ResearchEvidenceId'>;"
          },
          {
            "name": "ResearchEvidenceRequest",
            "declaration": "export interface ResearchEvidenceRequest {\n    readonly id: ResearchId;\n    readonly questionId: ResearchQuestionId;\n    readonly criterionIds?: string[] | undefined;\n    readonly source: string;\n    readonly url?: string | undefined;\n    readonly snippet?: string | undefined;\n    readonly sources?: ResearchEvidenceSource[] | undefined;\n    readonly claim: string;\n    readonly confidence: ResearchConfidence;\n    readonly status?: ResearchEvidenceStatus | undefined;\n}"
          },
          {
            "name": "ResearchEvidenceSource",
            "declaration": "export interface ResearchEvidenceSource {\n    readonly url: string;\n    readonly snippet: string;\n    readonly artifactId?: string | undefined;\n}"
          },
          {
            "name": "ResearchEvidenceStatus",
            "declaration": "export type ResearchEvidenceStatus = 'candidate' | 'accepted' | 'rejected';"
          },
          {
            "name": "ResearchFailRequest",
            "declaration": "export interface ResearchFailRequest {\n    readonly id: ResearchId;\n    readonly reason: string;\n    readonly aborted?: boolean;\n}"
          },
          {
            "name": "ResearchGetRequest",
            "declaration": "export interface ResearchGetRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchId",
            "declaration": "export type ResearchId = Branded<'ResearchId'>;"
          },
          {
            "name": "ResearchListRequest",
            "declaration": "export interface ResearchListRequest {\n    readonly query?: string;\n    readonly phase?: ResearchPhase;\n}"
          },
          {
            "name": "ResearchListResult",
            "declaration": "export interface ResearchListResult {\n    readonly projects: ResearchProject[];\n}"
          },
          {
            "name": "ResearchPhase",
            "declaration": "export type ResearchPhase = 'planning' | 'awaiting_plan_confirm' | 'investigating' | 'ready_for_report' | 'incomplete' | 'writing' | 'done' | 'failed' | 'aborted';"
          },
          {
            "name": "ResearchPlanUpdateRequest",
            "declaration": "export interface ResearchPlanUpdateRequest {\n    readonly id: ResearchId;\n    readonly goal: string;\n    readonly constraints: string;\n    readonly depth: ResearchDepth;\n    readonly questions: Array<{ readonly text: string; readonly criteria: string[]; readonly dependsOn?: number[]; }>;\n}"
          },
          {
            "name": "ResearchProgress",
            "declaration": "export interface ResearchProgress {\n    readonly running: number;\n    readonly waiting: number;\n    readonly scouts: ResearchScoutProgress[];\n}"
          },
          {
            "name": "ResearchProgressTool",
            "declaration": "export interface ResearchProgressTool {\n    readonly name: string;\n    readonly detail: string;\n    readonly status: 'running' | 'done';\n}"
          },
          {
            "name": "ResearchProject",
            "declaration": "export interface ResearchProject {\n    readonly id: ResearchId;\n    readonly title: string;\n    readonly question: string;\n    readonly goal: string;\n    readonly constraints: string;\n    readonly seedText: string;\n    readonly depth: ResearchDepth;\n    readonly phase: ResearchPhase;\n    readonly runState: ResearchRunState;\n    readonly planConfirmed: boolean;\n    readonly questions: ResearchQuestion[];\n    readonly evidence: ResearchEvidence[];\n    readonly conclusions: string[];\n    readonly limitations: string[];\n    readonly report: string | null;\n    readonly budget: ResearchBudget;\n    readonly progress: ResearchProgress;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "ResearchQuestion",
            "declaration": "export interface ResearchQuestion {\n    readonly id: ResearchQuestionId;\n    readonly text: string;\n    readonly dependsOn: ResearchQuestionId[];\n    readonly status: ResearchQuestionStatus;\n    readonly criteria: ResearchCriterion[];\n    readonly gaps: string[];\n    readonly handoff: string;\n}"
          },
          {
            "name": "ResearchQuestionId",
            "declaration": "export type ResearchQuestionId = Branded<'ResearchQuestionId'>;"
          },
          {
            "name": "ResearchQuestionStatus",
            "declaration": "export type ResearchQuestionStatus = 'pending' | 'running' | 'covered' | 'partial' | 'blocked' | 'failed';"
          },
          {
            "name": "ResearchQuestionUpdateRequest",
            "declaration": "export interface ResearchQuestionUpdateRequest {\n    readonly id: ResearchId;\n    readonly questionId: ResearchQuestionId;\n    readonly status: ResearchQuestionStatus;\n    readonly criteria?: ResearchCriterion[];\n}"
          },
          {
            "name": "ResearchResumeRequest",
            "declaration": "export interface ResearchResumeRequest {\n    readonly id: ResearchId;\n}"
          },
          {
            "name": "ResearchRunState",
            "declaration": "export type ResearchRunState = 'idle' | 'running' | 'paused';"
          },
          {
            "name": "ResearchScoutProgress",
            "declaration": "export interface ResearchScoutProgress {\n    readonly questionId: ResearchQuestionId;\n    readonly role: ResearchScoutRole;\n    readonly status: 'waiting' | 'running' | 'verifying' | 'done' | 'partial' | 'blocked';\n    readonly waitingOn: ResearchQuestionId[];\n    readonly toolsUsed: number;\n    readonly toolsCap: number;\n    readonly activity: string;\n    readonly tools: ResearchProgressTool[];\n    readonly scoutDraft: string;\n    readonly evaluatorDraft: string;\n    readonly activeCriterionId: string;\n    readonly activeCriterionText: string;\n    readonly dependencySummary: string;\n    readonly handoff: string;\n}"
          },
          {
            "name": "ResearchScoutRole",
            "declaration": "export type ResearchScoutRole = 'waiting' | 'scout' | 'evaluator' | 'writing';"
          },
          {
            "name": "ResearchStartRequest",
            "declaration": "export interface ResearchStartRequest {\n    readonly title?: string;\n    readonly question: string;\n    readonly goal?: string;\n    readonly constraints?: string;\n    readonly seedText?: string;\n    readonly depth: ResearchDepth;\n    readonly questions: Array<{ readonly text: string; readonly criteria: string[]; readonly dependsOn?: number[]; }>;\n}"
          },
          {
            "name": "ResearchVerification",
            "declaration": "export type ResearchVerification = '' | 'PASS' | 'WARNING' | 'FAIL';"
          },
          {
            "name": "ResearchWriteReportRequest",
            "declaration": "export interface ResearchWriteReportRequest {\n    readonly id: ResearchId;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Live project snapshot after each durable mutation so the workspace can refresh plans, scout tools, and agent drafts without polling.",
        "summary": "Live project snapshot after each durable mutation so the workspace can refresh plans, scout tools, and agent drafts without polling.",
        "tags": [
          {
            "name": "param",
            "argument": "project",
            "comment": "- detached project after the mutation.",
            "text": "@param project - detached project after the mutation.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Live project snapshot after each durable mutation so the workspace\n * can refresh plans, scout tools, and agent drafts without polling.\n * @param project - detached project after the mutation.\n * @mode emit\n */",
        "name": "deepResearch/progress",
        "mode": "emit",
        "signature": "'deepResearch/progress'(project: ResearchProject): void"
      }
    ],
    "objects": []
  },
}
