/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ResearchCompleteRequest, ResearchConfirmRequest, ResearchDeleteRequest, ResearchDeleteResult, ResearchEvidenceRequest, ResearchFailRequest, ResearchGetRequest, ResearchListRequest, ResearchListResult, ResearchPlanUpdateRequest, ResearchProject, ResearchQuestionUpdateRequest, ResearchResumeRequest, ResearchStartRequest, ResearchWriteReportRequest } from '@deepseek-ai/dsh-deepresearch/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$646565705265736561726368 {
    addEvidence: (request: ResearchEvidenceRequest) => Promise<RemoteResult<ResearchProject>>
    complete: (request: ResearchCompleteRequest) => Promise<RemoteResult<ResearchProject>>
    confirmPlan: (request: ResearchConfirmRequest) => Promise<RemoteResult<ResearchProject>>
    delete: (request: ResearchDeleteRequest) => Promise<RemoteResult<ResearchDeleteResult>>
    fail: (request: ResearchFailRequest) => Promise<RemoteResult<ResearchProject>>
    get: (request: ResearchGetRequest) => Promise<RemoteResult<ResearchProject | null>>
    list: (request: ResearchListRequest) => Promise<RemoteResult<ResearchListResult>>
    resume: (request: ResearchResumeRequest) => Promise<RemoteResult<ResearchProject>>
    start: (request: ResearchStartRequest) => Promise<RemoteResult<ResearchProject>>
    updatePlan: (request: ResearchPlanUpdateRequest) => Promise<RemoteResult<ResearchProject>>
    updateQuestion: (request: ResearchQuestionUpdateRequest) => Promise<RemoteResult<ResearchProject>>
    writeReport: (request: ResearchWriteReportRequest) => Promise<RemoteResult<ResearchProject>>
  }
  interface TypertRemoteMap {
    'deepResearch/addEvidence': (request: ResearchEvidenceRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/complete': (request: ResearchCompleteRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/confirmPlan': (request: ResearchConfirmRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/delete': (request: ResearchDeleteRequest) => Promise<RemoteResult<ResearchDeleteResult>>
    'deepResearch/fail': (request: ResearchFailRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/get': (request: ResearchGetRequest) => Promise<RemoteResult<ResearchProject | null>>
    'deepResearch/list': (request: ResearchListRequest) => Promise<RemoteResult<ResearchListResult>>
    'deepResearch/resume': (request: ResearchResumeRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/start': (request: ResearchStartRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/updatePlan': (request: ResearchPlanUpdateRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/updateQuestion': (request: ResearchQuestionUpdateRequest) => Promise<RemoteResult<ResearchProject>>
    'deepResearch/writeReport': (request: ResearchWriteReportRequest) => Promise<RemoteResult<ResearchProject>>
  }
  interface TypertRemoteNamespaceMap {
    'deepResearch': TypertRemoteNamespace$646565705265736561726368
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
