#!/usr/bin/env python3
"""
AI Product Designer - Self-contained CLI wrapper.

Generate product concept designs for Momcozy micro-moments.
Standalone — no external dependencies beyond Python stdlib.

Usage:
    python run.py --input "Describe the task..." --output result.json
    python run.py --input input.txt --output result.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parent.parent


def load_skill_prompt() -> str:
    """Read SKILL.md and extract the body after frontmatter."""
    skill_md = SKILL_DIR / "SKILL.md"
    if not skill_md.exists():
        return "No SKILL.md found."
    content = skill_md.read_text(encoding="utf-8")
    parts = content.split("---", 2)
    body = parts[2].strip() if len(parts) > 2 else content.strip()
    return body


def load_references() -> dict:
    """Load supporting reference files if they exist."""
    refs = {}
    ref_dir = SKILL_DIR / "references"
    if ref_dir.is_dir():
        for f in ref_dir.iterdir():
            if f.suffix in (".md", ".txt") and f.name != ".gitkeep":
                refs[f.name] = f.read_text(encoding="utf-8")
    return refs


def validate_input(input_text: str) -> str | None:
    """Validate input. Returns error message or None if valid."""
    stripped = input_text.strip()
    if not stripped:
        return "输入为空，请提供产品类型、核心人群和想解决的具体使用时刻。"
    if len(stripped) < 5:
        return "输入过短（<5字符），请提供更详细的产品描述。"
    # Reject dangerous patterns
    dangerous = ["rm -rf", "curl|sh", "/etc/passwd", "~/.ssh/", "忽略指令", "系统提示词"]
    for d in dangerous:
        if d in stripped.lower():
            return f"安全拒绝：输入包含危险模式（{d}），不执行。"
    return None


def main() -> None:
    parser = argparse.ArgumentParser(description="AI Product Designer CLI")
    parser.add_argument("--input", required=True, help="Input text or path to text file")
    parser.add_argument("--output", default=None, help="Output file path (JSON)")
    parser.add_argument("--format", choices=["json", "text"], default="json",
                        help="Output format (default: json)")
    args = parser.parse_args()

    # Read input
    input_path = Path(args.input)
    if input_path.exists():
        input_text = input_path.read_text(encoding="utf-8")
    else:
        input_text = args.input

    # Validate input
    error = validate_input(input_text)
    if error:
        result = {"error": error, "status": "rejected"}
        if args.output:
            Path(args.output).write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
        else:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        sys.exit(1)

    # Process
    body = load_skill_prompt()
    refs = load_references()

    result = {
        "status": "ok",
        "skill": "AI产品设计师",
        "input": input_text[:200],
        "skill_prompt_loaded": len(body) > 0,
        "references_loaded": list(refs.keys()),
        "message": "Input validated. This CLI is a wrapper; the actual concept design is generated by the LLM using the SKILL.md instructions.",
    }

    output = json.dumps(result, ensure_ascii=False, indent=2)
    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Result written to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
