/**
 * 共享层生成与漂移校验（ADR-0009：一份事实只有一个家）。
 *
 * 背景（A5）：若干受管包的 src/ 下有一批「生成副本」，其首行写着
 * 「Generated by scripts/sync-shared.mjs from shared/<path>」，但本仓库一度
 * **既没有 shared/ 源、也没有该生成器**。副本恰好逐字节相同，事实尚未分裂，
 * 但已无人能再改共享层——改一份即静默分叉。
 *
 * 本模块把该关系变成可机器校验的事实，且**不引入第二份清单**：
 * 消费方由「副本首行的标记」自描述，标记指向哪个 shared 路径就以哪个为准。
 * 因此新增消费方只需生成一次，无需在此登记。
 *
 * 契约：
 *   - `shared/<path>` 是唯一事实源，其自身**不含**标记行；
 *   - 副本内容必须逐字节等于 `标记行 + "\n" + shared 源内容`；
 *   - 标记指向的 shared 源不存在时**响亮失败**，绝不静默跳过。
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

/** 生成副本首行的标记（也是解析消费方的唯一依据）。 */
const MARKER = (sharedPath) =>
  `// Generated by scripts/sync-shared.mjs from ${sharedPath}. `
  + 'Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".'

/** 从副本首行解析出它声明的 shared 源路径；非生成副本返回 undefined。 */
export function parseSharedMarker(firstLine) {
  const m = /^\/\/ Generated by scripts\/sync-shared\.mjs from (\S+)\. Do not edit this copy; edit the shared source and run "node scripts\/sync-shared\.mjs"\.$/.exec(firstLine)
  return m === null ? undefined : m[1]
}

/** 收集 src/ 下所有文件（跳过 node_modules / lib / build / dist）。 */
function walkSourceFiles(dir, out = []) {
  if (!existsSync(dir)) return out
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'lib' || name === 'build' || name === 'dist') continue
    const full = join(dir, name)
    if (statSync(full).isDirectory()) walkSourceFiles(full, out)
    else out.push(full)
  }
  return out
}

/** 期望的副本内容：标记行 + 空行分隔 + 共享源正文。 */
export function expectedCopy(sharedPath, sharedBody) {
  return `${MARKER(sharedPath)}\n${sharedBody}`
}

/**
 * 扫描 packages/ 下的全部生成副本，逐个与共享源比对。
 * @returns {{consumers: Array<{copyPath: string, sharedPath: string, status: string, detail?: string}>, violations: string[]}}
 */
export function collectSharedConsumers(repoRoot) {
  const packagesDir = join(repoRoot, 'packages')
  const consumers = []
  const violations = []
  if (!existsSync(packagesDir)) return { consumers, violations }

  const groups = readdirSync(packagesDir)
    .filter((g) => statSync(join(packagesDir, g)).isDirectory())
    .sort()

  for (const group of groups) {
    const groupDir = join(packagesDir, group)
    for (const pkg of readdirSync(groupDir).sort()) {
      const srcDir = join(groupDir, pkg, 'src')
      if (!existsSync(srcDir)) continue
      for (const file of walkSourceFiles(srcDir)) {
        const text = readFileSync(file, 'utf8')
        const firstLine = text.slice(0, text.indexOf('\n') === -1 ? text.length : text.indexOf('\n'))
        const sharedPath = parseSharedMarker(firstLine)
        if (sharedPath === undefined) continue

        const relCopy = relative(repoRoot, file).split(sep).join('/')
        // 标记里的路径是**仓库相对**路径且自带 `shared/` 前缀（如 shared/host/http.ts）。
        const sharedAbs = join(repoRoot, sharedPath)

        if (!existsSync(sharedAbs)) {
          consumers.push({ copyPath: relCopy, sharedPath, status: 'missing-source' })
          violations.push(
            `${relCopy}: 声明来自 ${sharedPath}，但该共享源不存在`
            + '（生成器缺失会让副本静默分叉；补 shared/ 源或删除标记）',
          )
          continue
        }

        const expected = expectedCopy(sharedPath, readFileSync(sharedAbs, 'utf8'))
        if (text === expected) {
          consumers.push({ copyPath: relCopy, sharedPath, status: 'ok' })
        } else {
          consumers.push({ copyPath: relCopy, sharedPath, status: 'drift' })
          violations.push(
            `${relCopy}: 与 ${sharedPath} 不一致`
            + '（改共享层请改 shared/ 后跑 node scripts/sync-shared.mjs）',
          )
        }
      }
    }
  }
  return { consumers, violations }
}

/**
 * 门禁校验项：副本漂移或共享源缺失即失败。
 *
 * 「0 个消费方」刻意判为失败：标记语法一旦被改坏，正则再也匹配不到任何副本，
 * 这个校验就会**静默变成空转**——正是 A5 要根除的那类失管。
 */
export function checkSharedSync(repoRoot) {
  const { consumers, violations } = collectSharedConsumers(repoRoot)
  if (consumers.length === 0) {
    return {
      passed: false,
      violations: ['未发现任何生成副本——shared/ 机制形同虚设，或标记语法已失效（勿让校验静默空转）'],
    }
  }
  return { passed: violations.length === 0, violations }
}
